"""
Advanced Security & Threat Intelligence - Models
Covers alerts, indicators, vulnerabilities, and incident response.
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, Boolean, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship

from dario_app.database import Base


class ThreatIndicator(Base):
    """IOCs and threat intel indicators."""
    __tablename__ = "sec_threat_indicators"

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, nullable=False, index=True)

    indicator_type = Column(String(50))  # IP, Domain, URL, Hash
    value = Column(String(255), index=True)
    confidence = Column(Integer)  # 0-100
    source = Column(String(100))
    tags = Column(JSON)
    first_seen = Column(DateTime, default=datetime.utcnow)
    last_seen = Column(DateTime)
    is_active = Column(Boolean, default=True)

    created_at = Column(DateTime, default=datetime.utcnow)


class SecurityAlert(Base):
    """Security alert generated by detection systems."""
    __tablename__ = "sec_alerts"

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, nullable=False, index=True)

    alert_code = Column(String(50), unique=True, nullable=False, index=True)
    title = Column(String(200), nullable=False)
    severity = Column(String(50), default="Medium")  # Low, Medium, High, Critical
    category = Column(String(100))  # Malware, Phishing, Access, Misconfiguration
    source = Column(String(100))
    description = Column(Text)
    indicators = Column(JSON)  # referenced indicator IDs or values
    status = Column(String(50), default="New")  # New, In_Progress, Resolved, False_Positive

    detected_at = Column(DateTime, default=datetime.utcnow)
    acknowledged_at = Column(DateTime)
    resolved_at = Column(DateTime)
    owner = Column(String(100))

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Vulnerability(Base):
    """Vulnerability findings."""
    __tablename__ = "sec_vulnerabilities"

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, nullable=False, index=True)

    asset = Column(String(200))
    cve_id = Column(String(50), index=True)
    severity = Column(String(50))  # Low, Medium, High, Critical
    cvss_score = Column(Integer)
    status = Column(String(50), default="Open")  # Open, In_Remediation, Resolved
    remediation_owner = Column(String(100))
    remediation_plan = Column(Text)
    due_date = Column(DateTime)

    detected_at = Column(DateTime, default=datetime.utcnow)
    resolved_at = Column(DateTime)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class Incident(Base):
    """Security incident record with phases."""
    __tablename__ = "sec_incidents"

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, nullable=False, index=True)

    incident_code = Column(String(50), unique=True, nullable=False, index=True)
    title = Column(String(200))
    description = Column(Text)
    severity = Column(String(50), default="Medium")
    category = Column(String(100))
    status = Column(String(50), default="Identified")  # Identified, Contained, Eradicated, Recovered, Closed
    impact = Column(String(100))
    affected_assets = Column(JSON)

    detected_at = Column(DateTime, default=datetime.utcnow)
    contained_at = Column(DateTime)
    recovered_at = Column(DateTime)
    closed_at = Column(DateTime)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class SecurityAssessment(Base):
    """Periodic security assessments and compliance checks."""
    __tablename__ = "sec_assessments"

    id = Column(Integer, primary_key=True, index=True)
    organization_id = Column(Integer, nullable=False, index=True)

    assessment_code = Column(String(50), unique=True, nullable=False, index=True)
    framework = Column(String(100))  # CIS, NIST, ISO27001
    scope = Column(String(200))
    status = Column(String(50), default="Planned")  # Planned, In_Progress, Completed
    score = Column(Integer)
    findings = Column(JSON)
    recommendations = Column(JSON)

    started_at = Column(DateTime)
    completed_at = Column(DateTime)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
