"""Tutorial steps definition - Synced with current dashboard modules."""

TUTORIAL_STEPS = [
    {
        "step": 1,
        "title": "🎉 ¡Bienvenido al ERP Dario!",
        "description": "Tour rápido por el dashboard unificado: iconos claros, sin despliegues por hover y botones consistentes.",
        "selector": "body",
        "position": "center",
        "highlight": False,
        "action_text": "Comenzar",
        "image_url": None,
    },
    {
        "step": 2,
        "title": "📊 Dashboard y KPIs",
        "description": "Métricas clave: ventas del mes, órdenes pendientes, usuarios activos y stock. Todo visible sin capas ocultas.",
        "selector": ".stats",
        "position": "bottom",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 3,
        "title": "💳 POS",
        "description": "Caja rápida y widgets para ecommerce. Acceso directo con tarjeta uniforme (icono + título).",
        "selector": ".modules .module-card:nth-child(1)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 4,
        "title": "📦 Inventario",
        "description": "Stock, mínimos y alertas. Integra proveedores y sincroniza con compras/ventas.",
        "selector": ".modules .module-card:nth-child(2)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 5,
        "title": "🏭 Almacén",
        "description": "Ubicaciones, movimientos y picking. Todo con la misma paleta y botones estándar.",
        "selector": ".modules .module-card:nth-child(3)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 6,
        "title": "🔧 Oficina Técnica",
        "description": "BOMs, variantes y documentación técnica consolidada.",
        "selector": ".modules .module-card:nth-child(4)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 7,
        "title": "📋 Producción (Órdenes)",
        "description": "Planifica órdenes de fabricación y seguimiento de etapas.",
        "selector": ".modules .module-card:nth-child(5)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 8,
        "title": "🛠️ Mi Producción",
        "description": "Trabajo del operario: tareas asignadas, partes y avances.",
        "selector": ".modules .module-card:nth-child(6)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 9,
        "title": "🚚 Logística",
        "description": "Envíos, tracking y transportistas. Tarjetas sin hover, colores uniformes.",
        "selector": ".modules .module-card:nth-child(7)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 10,
        "title": "🛠️ Field Service",
        "description": "Órdenes de servicio, agenda y SLA para técnicos en campo.",
        "selector": ".modules .module-card:nth-child(8)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 11,
        "title": "🗂️ Proyectos",
        "description": "Project Ops: tareas, tiempos y facturación en una vista uniforme.",
        "selector": ".modules .module-card:nth-child(9)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 12,
        "title": "🎧 Soporte",
        "description": "Customer Service: casos, base de conocimiento y entitlements.",
        "selector": ".modules .module-card:nth-child(10)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 13,
        "title": "📢 Marketing",
        "description": "Campañas, journeys y plantillas. Sin efectos por hover, todo claro.",
        "selector": ".modules .module-card:nth-child(11)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 14,
        "title": "🔗 Supply Chain",
        "description": "MRP, políticas de reposición y landed cost en una sola interfaz clara.",
        "selector": ".modules .module-card:nth-child(12)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 15,
        "title": "🚪 Puertas",
        "description": "Verificación de puertas y controles específicos del proceso.",
        "selector": ".modules .module-card:nth-child(13)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 16,
        "title": "💰 Ventas",
        "description": "Pipeline de ventas y facturación, unificado con la paleta global.",
        "selector": ".modules .module-card:nth-child(14)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 17,
        "title": "🛒 Compras",
        "description": "Órdenes de compra, recepción y costos por proveedor.",
        "selector": ".modules .module-card:nth-child(15)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 18,
        "title": "📄 Documentos",
        "description": "Plantillas y documentos (facturas, albaranes, manuales) con acciones visibles siempre.",
        "selector": ".modules .module-card:nth-child(16)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 19,
        "title": "📒 Contabilidad",
        "description": "Asientos, balances y libros contables. Paleta y botones coherentes.",
        "selector": ".modules .module-card:nth-child(17)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 20,
        "title": "🏦 Finanzas",
        "description": "Presupuestos, conciliación y cash-flow con botones estándar.",
        "selector": ".modules .module-card:nth-child(18)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 21,
        "title": "🧑‍💼 RRHH",
        "description": "Empleados, vacaciones, nómina y partes.",
        "selector": ".modules .module-card:nth-child(19)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 22,
        "title": "⚙️ Configuración",
        "description": "Datos de empresa, impuestos, monedas y ajustes generales.",
        "selector": ".modules .module-card:nth-child(20)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 23,
        "title": "📊 Análisis",
        "description": "Reportes y dashboards avanzados con la misma paleta en todo el recorrido.",
        "selector": ".modules .module-card:nth-child(21)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 24,
        "title": "📧 Correo",
        "description": "SMTP y plantillas de correo. Gestión sencilla y directa.",
        "selector": ".modules .module-card:nth-child(22)",
        "position": "right",
        "highlight": True,
        "action_text": "Siguiente",
        "image_url": None,
    },
    {
        "step": 25,
        "title": "🚀 ¡Listo para empezar!",
        "description": "Todo el dashboard usa colores unificados y sin efectos hover. Pulsa el botón de ayuda si quieres repetir el tour.",
        "selector": "body",
        "position": "center",
        "highlight": False,
        "action_text": "Finalizar tutorial",
        "image_url": None,
    },
]


def get_tutorial_steps():
    """Get all tutorial steps."""
    return TUTORIAL_STEPS


def get_step(step_number: int):
    """Get specific tutorial step."""
    for step in TUTORIAL_STEPS:
        if step["step"] == step_number:
            return step
    return None
