"""Bombas Omni - Complete ERP seed data for all modules."""

from datetime import datetime, timedelta
import random

# ============================================
# PRODUCTOS E INVENTARIO
# ============================================

PRODUCTOS_INVENTARIO = [
    # Bombas finales (productos terminados)
    {
        "sku": "BC-100",
        "nombre": "Bomba Centrífuga BC-100",
        "categoria": "Bombas",
        "subcategoria": "Centrífugas",
        "precio_venta": 450.00,
        "precio_compra": 280.00,
        "stock": 12,
        "stock_minimo": 5,
        "ubicacion": "ALMACEN-PT-A1",
        "proveedor": None,  # Fabricación propia
    },
    {
        "sku": "BS-200",
        "nombre": "Bomba Sumergible BS-200",
        "categoria": "Bombas",
        "subcategoria": "Sumergibles",
        "precio_venta": 680.00,
        "precio_compra": 420.00,
        "stock": 8,
        "stock_minimo": 3,
        "ubicacion": "ALMACEN-PT-A2",
        "proveedor": None,
    },
    {
        "sku": "BA-150",
        "nombre": "Bomba Autoaspirante BA-150",
        "categoria": "Bombas",
        "subcategoria": "Autoaspirantes",
        "precio_venta": 520.00,
        "precio_compra": 310.00,
        "stock": 15,
        "stock_minimo": 6,
        "ubicacion": "ALMACEN-PT-A3",
        "proveedor": None,
    },
    {
        "sku": "BD-300",
        "nombre": "Bomba Diésel BD-300",
        "categoria": "Bombas",
        "subcategoria": "Diésel",
        "precio_venta": 1250.00,
        "precio_compra": 850.00,
        "stock": 4,
        "stock_minimo": 2,
        "ubicacion": "ALMACEN-PT-B1",
        "proveedor": None,
    },
    {
        "sku": "BP-180",
        "nombre": "Bomba de Presión BP-180",
        "categoria": "Bombas",
        "subcategoria": "Presión",
        "precio_venta": 590.00,
        "precio_compra": 360.00,
        "stock": 10,
        "stock_minimo": 4,
        "ubicacion": "ALMACEN-PT-B2",
        "proveedor": None,
    },
    {
        "sku": "BI-500",
        "nombre": "Bomba Industrial BI-500",
        "categoria": "Bombas",
        "subcategoria": "Industrial",
        "precio_venta": 2100.00,
        "precio_compra": 1400.00,
        "stock": 3,
        "stock_minimo": 1,
        "ubicacion": "ALMACEN-PT-B3",
        "proveedor": None,
    },
    
    # Componentes - Motores
    {
        "sku": "MOT-E-1HP",
        "nombre": "Motor Eléctrico 1HP",
        "categoria": "Componentes",
        "subcategoria": "Motores",
        "precio_venta": 85.00,
        "precio_compra": 65.00,
        "stock": 45,
        "stock_minimo": 20,
        "ubicacion": "ALMACEN-C-M1",
        "proveedor": "Motores Ibérica S.A.",
    },
    {
        "sku": "MOT-E-1.5HP",
        "nombre": "Motor Eléctrico 1.5HP",
        "categoria": "Componentes",
        "subcategoria": "Motores",
        "precio_venta": 95.00,
        "precio_compra": 72.00,
        "stock": 38,
        "stock_minimo": 15,
        "ubicacion": "ALMACEN-C-M1",
        "proveedor": "Motores Ibérica S.A.",
    },
    {
        "sku": "MOT-E-1.8HP",
        "nombre": "Motor Eléctrico 1.8HP",
        "categoria": "Componentes",
        "subcategoria": "Motores",
        "precio_venta": 105.00,
        "precio_compra": 78.00,
        "stock": 12,  # Stock bajo - alerta
        "stock_minimo": 15,
        "ubicacion": "ALMACEN-C-M1",
        "proveedor": "Motores Ibérica S.A.",
    },
    {
        "sku": "MOT-E-2HP",
        "nombre": "Motor Eléctrico 2HP",
        "categoria": "Componentes",
        "subcategoria": "Motores",
        "precio_venta": 115.00,
        "precio_compra": 85.00,
        "stock": 32,
        "stock_minimo": 12,
        "ubicacion": "ALMACEN-C-M2",
        "proveedor": "Motores Ibérica S.A.",
    },
    {
        "sku": "MOT-E-5HP",
        "nombre": "Motor Eléctrico 5HP",
        "categoria": "Componentes",
        "subcategoria": "Motores",
        "precio_venta": 280.00,
        "precio_compra": 210.00,
        "stock": 18,
        "stock_minimo": 8,
        "ubicacion": "ALMACEN-C-M2",
        "proveedor": "Motores Ibérica S.A.",
    },
    {
        "sku": "MOT-D-3HP",
        "nombre": "Motor Diésel 3HP",
        "categoria": "Componentes",
        "subcategoria": "Motores",
        "precio_venta": 450.00,
        "precio_compra": 340.00,
        "stock": 8,
        "stock_minimo": 4,
        "ubicacion": "ALMACEN-C-M3",
        "proveedor": "Diésel Power S.L.",
    },
    
    # Chasis
    {
        "sku": "CHS-P",
        "nombre": "Chasis Pequeño",
        "categoria": "Componentes",
        "subcategoria": "Estructura",
        "precio_venta": 35.00,
        "precio_compra": 22.00,
        "stock": 65,
        "stock_minimo": 30,
        "ubicacion": "ALMACEN-C-CH1",
        "proveedor": "Metalúrgica del Sur",
    },
    {
        "sku": "CHS-M",
        "nombre": "Chasis Mediano",
        "categoria": "Componentes",
        "subcategoria": "Estructura",
        "precio_venta": 48.00,
        "precio_compra": 30.00,
        "stock": 52,
        "stock_minimo": 25,
        "ubicacion": "ALMACEN-C-CH1",
        "proveedor": "Metalúrgica del Sur",
    },
    {
        "sku": "CHS-G",
        "nombre": "Chasis Grande",
        "categoria": "Componentes",
        "subcategoria": "Estructura",
        "precio_venta": 72.00,
        "precio_compra": 48.00,
        "stock": 28,
        "stock_minimo": 12,
        "ubicacion": "ALMACEN-C-CH2",
        "proveedor": "Metalúrgica del Sur",
    },
    
    # Manguitos
    {
        "sku": "MNG-50",
        "nombre": "Manguito Unión 50mm",
        "categoria": "Componentes",
        "subcategoria": "Fontanería",
        "precio_venta": 8.50,
        "precio_compra": 5.20,
        "stock": 180,
        "stock_minimo": 80,
        "ubicacion": "ALMACEN-C-FT1",
        "proveedor": "Hidráulica Central",
    },
    {
        "sku": "MNG-75",
        "nombre": "Manguito Unión 75mm",
        "categoria": "Componentes",
        "subcategoria": "Fontanería",
        "precio_venta": 12.00,
        "precio_compra": 7.50,
        "stock": 145,
        "stock_minimo": 60,
        "ubicacion": "ALMACEN-C-FT1",
        "proveedor": "Hidráulica Central",
    },
    {
        "sku": "MNG-100",
        "nombre": "Manguito Unión 100mm",
        "categoria": "Componentes",
        "subcategoria": "Fontanería",
        "precio_venta": 18.00,
        "precio_compra": 11.00,
        "stock": 95,
        "stock_minimo": 40,
        "ubicacion": "ALMACEN-C-FT2",
        "proveedor": "Hidráulica Central",
    },
    
    # Hélices
    {
        "sku": "HLC-5",
        "nombre": "Hélice 5 palas",
        "categoria": "Componentes",
        "subcategoria": "Impulsor",
        "precio_venta": 24.00,
        "precio_compra": 16.00,
        "stock": 88,
        "stock_minimo": 40,
        "ubicacion": "ALMACEN-C-HL1",
        "proveedor": "Fundiciones Técnicas",
    },
    {
        "sku": "HLC-6",
        "nombre": "Hélice 6 palas",
        "categoria": "Componentes",
        "subcategoria": "Impulsor",
        "precio_venta": 28.00,
        "precio_compra": 18.50,
        "stock": 76,
        "stock_minimo": 35,
        "ubicacion": "ALMACEN-C-HL1",
        "proveedor": "Fundiciones Técnicas",
    },
    {
        "sku": "HLC-8",
        "nombre": "Hélice 8 palas reforzada",
        "categoria": "Componentes",
        "subcategoria": "Impulsor",
        "precio_venta": 48.00,
        "precio_compra": 32.00,
        "stock": 42,
        "stock_minimo": 15,
        "ubicacion": "ALMACEN-C-HL2",
        "proveedor": "Fundiciones Técnicas",
    },
    
    # Kits fontanería
    {
        "sku": "FTN-KIT-P",
        "nombre": "Kit Fontanería Pequeño",
        "categoria": "Componentes",
        "subcategoria": "Fontanería",
        "precio_venta": 15.00,
        "precio_compra": 9.50,
        "stock": 110,
        "stock_minimo": 50,
        "ubicacion": "ALMACEN-C-FT3",
        "proveedor": "Hidráulica Central",
    },
    {
        "sku": "FTN-KIT-M",
        "nombre": "Kit Fontanería Mediano",
        "categoria": "Componentes",
        "subcategoria": "Fontanería",
        "precio_venta": 22.00,
        "precio_compra": 14.00,
        "stock": 92,
        "stock_minimo": 40,
        "ubicacion": "ALMACEN-C-FT3",
        "proveedor": "Hidráulica Central",
    },
    {
        "sku": "FTN-KIT-G",
        "nombre": "Kit Fontanería Grande",
        "categoria": "Componentes",
        "subcategoria": "Fontanería",
        "precio_venta": 35.00,
        "precio_compra": 22.00,
        "stock": 58,
        "stock_minimo": 20,
        "ubicacion": "ALMACEN-C-FT4",
        "proveedor": "Hidráulica Central",
    },
    
    # Tornillería
    {
        "sku": "TRN-M8",
        "nombre": "Tornillos M8 (pack 50)",
        "categoria": "Componentes",
        "subcategoria": "Tornillería",
        "precio_venta": 4.50,
        "precio_compra": 2.80,
        "stock": 350,
        "stock_minimo": 150,
        "ubicacion": "ALMACEN-C-TR1",
        "proveedor": "Ferretería Industrial",
    },
    {
        "sku": "TRN-M10",
        "nombre": "Tornillos M10 (pack 50)",
        "categoria": "Componentes",
        "subcategoria": "Tornillería",
        "precio_venta": 5.50,
        "precio_compra": 3.50,
        "stock": 280,
        "stock_minimo": 120,
        "ubicacion": "ALMACEN-C-TR1",
        "proveedor": "Ferretería Industrial",
    },
    {
        "sku": "ARN-M8",
        "nombre": "Arandelas M8 (pack 100)",
        "categoria": "Componentes",
        "subcategoria": "Tornillería",
        "precio_venta": 3.20,
        "precio_compra": 1.90,
        "stock": 420,
        "stock_minimo": 200,
        "ubicacion": "ALMACEN-C-TR2",
        "proveedor": "Ferretería Industrial",
    },
    {
        "sku": "ARN-M10",
        "nombre": "Arandelas M10 (pack 100)",
        "categoria": "Componentes",
        "subcategoria": "Tornillería",
        "precio_venta": 3.80,
        "precio_compra": 2.30,
        "stock": 385,
        "stock_minimo": 180,
        "ubicacion": "ALMACEN-C-TR2",
        "proveedor": "Ferretería Industrial",
    },
    {
        "sku": "JNT-NBR",
        "nombre": "Juntas NBR (pack 10)",
        "categoria": "Componentes",
        "subcategoria": "Sellado",
        "precio_venta": 6.50,
        "precio_compra": 4.00,
        "stock": 210,
        "stock_minimo": 100,
        "ubicacion": "ALMACEN-C-SL1",
        "proveedor": "Hidráulica Central",
    },
]

# ============================================
# CLIENTES
# ============================================

CLIENTES = [
    {
        "nombre": "Agrícola Los Pinos S.L.",
        "cif": "B12345678",
        "email": "compras@agricolalospinos.es",
        "telefono": "+34 967 123 456",
        "direccion": "Ctra. Albacete km 45, Hellín",
        "tipo": "empresa",
        "descuento": 10,  # 10% descuento
    },
    {
        "nombre": "Construcciones Martínez",
        "cif": "B87654321",
        "email": "admin@construccionesmartinez.com",
        "telefono": "+34 967 234 567",
        "direccion": "C/ Industrial 23, Tobarra",
        "tipo": "empresa",
        "descuento": 8,
    },
    {
        "nombre": "Instalaciones Hidráulicas del Sureste",
        "cif": "B55443322",
        "email": "info@hidraulicasureste.es",
        "telefono": "+34 967 345 678",
        "direccion": "Polígono Los Llanos, Almansa",
        "tipo": "empresa",
        "descuento": 12,
    },
    {
        "nombre": "Juan García Pérez",
        "dni": "12345678A",
        "email": "juangarcia@email.com",
        "telefono": "+34 678 123 456",
        "direccion": "C/ Mayor 15, Hellín",
        "tipo": "particular",
        "descuento": 0,
    },
    {
        "nombre": "Piscinas y Jardines Mediterráneo",
        "cif": "B99887766",
        "email": "ventas@piscinasmediterraneo.com",
        "telefono": "+34 967 456 789",
        "direccion": "Avda. Constitución 88, Albacete",
        "tipo": "empresa",
        "descuento": 15,
    },
    {
        "nombre": "Cooperativa Agricultores Unidos",
        "cif": "F11223344",
        "email": "cooperativa@agricultoresunidos.es",
        "telefono": "+34 967 567 890",
        "direccion": "Plaza Mayor 1, Villarrobledo",
        "tipo": "cooperativa",
        "descuento": 18,
    },
    {
        "nombre": "María López Sánchez",
        "dni": "87654321B",
        "email": "mlopez@email.com",
        "telefono": "+34 678 234 567",
        "direccion": "C/ Rosario 42, Tobarra",
        "tipo": "particular",
        "descuento": 0,
    },
    {
        "nombre": "Minera Hellín S.A.",
        "cif": "A55667788",
        "email": "compras@minerahellin.es",
        "telefono": "+34 967 678 901",
        "direccion": "Ctra. N-301 km 234, Hellín",
        "tipo": "empresa",
        "descuento": 20,  # Cliente VIP
    },
]

# ============================================
# PROVEEDORES
# ============================================

PROVEEDORES = [
    {
        "nombre": "Motores Ibérica S.A.",
        "cif": "A11111111",
        "email": "ventas@motoresiberica.com",
        "telefono": "+34 91 123 4567",
        "direccion": "Polígono Industrial Norte, Madrid",
        "categoria": "Motores",
        "plazo_pago": 60,  # días
    },
    {
        "nombre": "Diésel Power S.L.",
        "cif": "B22222222",
        "email": "comercial@dieselpower.es",
        "telefono": "+34 96 234 5678",
        "direccion": "C/ Industria 45, Valencia",
        "categoria": "Motores Diésel",
        "plazo_pago": 90,
    },
    {
        "nombre": "Metalúrgica del Sur",
        "cif": "B33333333",
        "email": "pedidos@metalurgicadelsur.es",
        "telefono": "+34 95 345 6789",
        "direccion": "Avda. Metalurgia 12, Sevilla",
        "categoria": "Estructuras Metálicas",
        "plazo_pago": 30,
    },
    {
        "nombre": "Hidráulica Central",
        "cif": "B44444444",
        "email": "info@hidraulicacentral.com",
        "telefono": "+34 96 456 7890",
        "direccion": "Polígono Los Olivares, Alicante",
        "categoria": "Fontanería y Accesorios",
        "plazo_pago": 45,
    },
    {
        "nombre": "Fundiciones Técnicas",
        "cif": "B55555555",
        "email": "ventas@fundicionestecnicas.es",
        "telefono": "+34 94 567 8901",
        "direccion": "C/ Fundición 78, Bilbao",
        "categoria": "Piezas Fundidas",
        "plazo_pago": 60,
    },
    {
        "nombre": "Ferretería Industrial",
        "cif": "B66666666",
        "email": "pedidos@ferrind.com",
        "telefono": "+34 93 678 9012",
        "direccion": "Polígono Can Jardinets, Barcelona",
        "categoria": "Tornillería y Ferretería",
        "plazo_pago": 30,
    },
    {
        "nombre": "Mecanizados Pérez S.L.",
        "cif": "B77777777",
        "email": "taller@mecanizadosperez.es",
        "telefono": "+34 967 789 012",
        "direccion": "C/ Taller 5, Albacete",
        "categoria": "Mecanizado Externo",
        "plazo_pago": 30,
    },
]

# ============================================
# VENTAS RECIENTES
# ============================================

VENTAS_EJEMPLO = [
    {
        "fecha": datetime.now() - timedelta(days=2),
        "cliente": "Agrícola Los Pinos S.L.",
        "productos": [
            {"sku": "BD-300", "cantidad": 2, "precio_unitario": 1125.00},  # Con descuento 10%
        ],
        "subtotal": 2250.00,
        "descuento": 225.00,
        "iva": 425.25,
        "total": 2450.25,
        "estado": "pagado",
    },
    {
        "fecha": datetime.now() - timedelta(days=5),
        "cliente": "Piscinas y Jardines Mediterráneo",
        "productos": [
            {"sku": "BA-150", "cantidad": 4, "precio_unitario": 442.00},  # Con descuento 15%
            {"sku": "BP-180", "cantidad": 2, "precio_unitario": 501.50},
        ],
        "subtotal": 2771.00,
        "descuento": 415.65,
        "iva": 494.12,
        "total": 2849.47,
        "estado": "pagado",
    },
    {
        "fecha": datetime.now() - timedelta(days=1),
        "cliente": "Juan García Pérez",
        "productos": [
            {"sku": "BC-100", "cantidad": 1, "precio_unitario": 450.00},
        ],
        "subtotal": 450.00,
        "descuento": 0.00,
        "iva": 94.50,
        "total": 544.50,
        "estado": "pendiente",
    },
    {
        "fecha": datetime.now() - timedelta(days=7),
        "cliente": "Minera Hellín S.A.",
        "productos": [
            {"sku": "BI-500", "cantidad": 3, "precio_unitario": 1680.00},  # Con descuento 20%
        ],
        "subtotal": 5040.00,
        "descuento": 1008.00,
        "iva": 846.72,
        "total": 4878.72,
        "estado": "pagado",
    },
]

# ============================================
# COMPRAS RECIENTES
# ============================================

COMPRAS_EJEMPLO = [
    {
        "fecha": datetime.now() - timedelta(days=3),
        "proveedor": "Motores Ibérica S.A.",
        "productos": [
            {"sku": "MOT-E-2HP", "cantidad": 20, "precio_unitario": 85.00},
            {"sku": "MOT-E-5HP", "cantidad": 10, "precio_unitario": 210.00},
        ],
        "subtotal": 3800.00,
        "iva": 798.00,
        "total": 4598.00,
        "estado": "recibido",
        "fecha_pago_prevista": datetime.now() + timedelta(days=57),
    },
    {
        "fecha": datetime.now() - timedelta(days=10),
        "proveedor": "Hidráulica Central",
        "productos": [
            {"sku": "MNG-75", "cantidad": 100, "precio_unitario": 7.50},
            {"sku": "FTN-KIT-M", "cantidad": 50, "precio_unitario": 14.00},
        ],
        "subtotal": 1450.00,
        "iva": 304.50,
        "total": 1754.50,
        "estado": "recibido",
        "fecha_pago_prevista": datetime.now() + timedelta(days=35),
    },
]
